[package]
name = "binary_search_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "binary_search_rs"

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
numpy = "0.20"
